apiVersion: apps/v1
kind: Deployment
metadata:
  name: navy-deployment
  labels:
    app: navy-web-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: navy-web-app
  template:
    metadata:
      labels:
        app: navy-web-app
    spec:
      containers:
      - name: my-httpd-cont
        image: mohitsoniv/httpd:webappNavy
