apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-required
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: type
            operator: In
            values:
            - high-performance
  containers:
  - name: nginx
    image: nginx:1.21
    ports:
    - containerPort: 80

