apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXIuaW8iOnsidXNlcm5hbWUiOiJtb2hpdG9zbml2IiwicGFzc3dvcmQiOiJBQG1vaGl0IiwiZW1haWwiOiJtb2hpdHNvbmkuODQ0NUBnbWFpbC5jb20iLCJhdXRoIjoiYlc5b2FYUnZjMjVwZGpwQlFHMXZhR2wwIn19fQ==
kind: Secret
metadata:
  creationTimestamp: "2024-08-30T07:41:31Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:.dockerconfigjson: {}
      f:type: {}
    manager: kubectl-create
    operation: Update
    time: "2024-08-30T07:41:31Z"
  name: my-registry-secret
  namespace: default
  resourceVersion: "110196"
  selfLink: /api/v1/namespaces/default/secrets/my-registry-secret
  uid: 317f0ff1-40e2-4e71-b42f-20fcccd2a087
type: kubernetes.io/dockerconfigjson
