# this file is created from kubectl get secret my-manifest-secret -o yaml > my-manifest-scrt.yaml
apiVersion: v1
data:
  password: UEBzc3cwcmQ=
  username: YWRtaW4=
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"password":"UEBzc3cwcmQ=","username":"YWRtaW4="},"kind":"Secret","metadata":{"annotations":{},"name":"my-manifest-secret","namespace":"default"},"type":"Opaque"}
  creationTimestamp: "2024-08-30T07:58:09Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:password: {}
        f:username: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:type: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2024-08-30T07:58:09Z"
  name: my-manifest-secret
  namespace: default
  resourceVersion: "112626"
  selfLink: /api/v1/namespaces/default/secrets/my-manifest-secret
  uid: 35d54ec8-3532-4c1b-8c98-1e51d226fe36
type: Opaque
