apiVersion: v1
kind: Pod
metadata:
  name: multi-container2-pod
  labels:
    app: multi-container2-app
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
    - name: ubuntu-container
      image: ubuntu:latest
      command: ["sh", "-c", "while true; do echo hello from the ubuntu container; sleep 3600; done"]
