apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  labels:
    app: multi-container-app
spec:
  containers:
  - name: navy-container
    image: mohitsoniv/httpd:webappNavy
  - name: pink-container
    image: mohitsoniv/ubuntu:webappPink

